In [1]:
import pandas as pd

df = pd.read_excel("caprae.xlsx")
df  # This will display the DataFrame in a table format in Jupyter Notebook

,Unnamed: 0,Group,MTBC0:6446,MTBC0:171253,MTBC0:200778,MTBC0:256534,MTBC0:289816,MTBC0:303421,MTBC0:409111,MTBC0:492365,...,MTBC0:45941,MTBC0:816295,MTBC0:1648444,MTBC0:2563063,MTBC0:3169077,MTBC0:400234,MTBC0:724802,MTBC0:839837,MTBC0:1512584,MTBC0:1954442
0,root,NaN,G,A,T,G,G,C,C,C,...,A,A,C,T,T,T,A,T,A,A
1,SRR13888787_Spain_Goat,La2.1 Iberian,T,C,C,C,T,T,A,T,...,A,A,C,T,T,T,A,T,A,A
2,SRR23911107,La2.1 Iberian,T,C,C,C,T,T,A,T,...,A,A,C,T,T,T,A,T,A,A
3,ERR10430703_Spain_Human,La2.1 Iberian,T,C,C,C,T,T,A,T,...,A,A,C,T,T,T,A,T,A,A
4,SRR23911112_Portugal_Cattle,La2.1 Iberian,T,C,C,C,T,T,A,T,...,A,A,C,T,T,T,A,T,A,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,IVRI-54,La2.3_Asian,T,C,C,C,T,T,A,T,...,A,A,C,T,T,C,G,C,G,G
260,IVRI-34,La2.3_Asian,T,C,C,C,T,T,A,T,...,A,A,C,T,T,C,G,C,G,G
261,IVRI-28,La2.3_Asian,T,C,C,C,T,T,A,T,...,A,A,C,T,T,C,G,C,G,G
262,MQ,NaN,59.901235,59.91358,59.882716,59.843621,59.907407,59.91358,59.901235,59.87037,...,60,60,60,60,60,60,60,59.8,60,60
263,annotation,NaN,"GCG->TCG, gyrB:A403S, mtbc0_000005, nonsynonymous","CGA->CGC, unlisted gene:R139R, mtbc0_000155, s...","ATC->ACC, unlisted gene:I179T, mtbc0_000183, n...","GGC->GCC, fadD4:G8A, mtbc0_000228, nonsynonymous","GCT->TCT, unlisted gene:A31S, mtbc0_000256, no...","GGC->GGT, nirB:G58G, mtbc0_000268, silent muta...","GTG->GTT, unlisted gene:V18V, mtbc0_000358, si...",position not annotated,...,"ACG->GCG, leuS:T761A, mtbc0_000046, nonsynonymous","TAC->TGC, rplE:Y15C, mtbc0_000758, nonsynonymous","TAC->TAA, unlisted gene:Y104_, mtbc0_001555, n...","AGG->GGG, unlisted gene:R465G, mtbc0_002406, n...","AGC->GGC, nusA:S340G, mtbc0_003020, nonsynonymous","GGT->GGC, unlisted gene:G237G, mtbc0_000351, s...","TCG->CCG, recD:S162P, mtbc0_000662, nonsynonymous",position not annotated,"CAC->CGC, unlisted gene:H95R, mtbc0_001430, no...","CAC->CGC, unlisted gene:H192R, mtbc0_001824, n..."